# Generated by Django 3.0.8 on 2020-07-05 13:29

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Must be a valid email address. This is what you will use to log in.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
